name: Deploy Website to Production

# Trigger: Se activa en cada push a la rama 'master'
on:
  push:
    branches:
      - master

# Jobs: Define los trabajos a ejecutar
jobs:
  deploy:
    # Usamos la última versión de Ubuntu que ofrece GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Desplegar archivos de la web con rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          # Directorio fuente en el repo (¡la barra al final es importante!)
          SOURCE: "website/"
          # Directorio destino en el servidor
          TARGET: "/srv/portfolio/website"
          # Excluir archivos innecesarios para más seguridad
          EXCLUDE: "/.git/, /.github/, /ansible/, /node_modules/"
          # Opciones de rsync:
          # -r: recursivo
          # -l: copia enlaces simbólicos
          # -t: preserva tiempos de modificación
          # -z: comprime los datos
          # -v: modo verbose (más información en los logs)
          # --delete: borra en el destino los archivos que ya no existen en la fuente
          ARGS: "-rltzv --delete" 